""" This is the file created by Python when translating the .ui file to .py file.
You can always update this file (but this comments will be erased) by using the next command:

pyuic5 <filename.ui> -o <filename.py>

for this case was done in this specific form "pyuic5 main_window.ui -o main_window.py".
I decided to name all the widgets (controllers and indicators) in a mixedCased form to match
the same name convention used by PyQt5.
"""


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonStop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStop.setGeometry(QtCore.QRect(35, 373, 521, 51))
        self.buttonStop.setObjectName("buttonStop")
        self.titleUI = QtWidgets.QLabel(self.centralwidget)
        self.titleUI.setGeometry(QtCore.QRect(100, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleUI.setFont(font)
        self.titleUI.setObjectName("titleUI")
        self.titleMoving = QtWidgets.QLabel(self.centralwidget)
        self.titleMoving.setGeometry(QtCore.QRect(250, 160, 64, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleMoving.setFont(font)
        self.titleMoving.setObjectName("titleMoving")
        self.titleController = QtWidgets.QLabel(self.centralwidget)
        self.titleController.setGeometry(QtCore.QRect(40, 80, 64, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleController.setFont(font)
        self.titleController.setObjectName("titleController")
        self.selectController = QtWidgets.QComboBox(self.centralwidget)
        self.selectController.setGeometry(QtCore.QRect(40, 104, 161, 21))
        self.selectController.setCurrentText("")
        self.selectController.setPlaceholderText("")
        self.selectController.setObjectName("selectController")
        self.buttonDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDisconnect.setGeometry(QtCore.QRect(320, 100, 81, 24))
        self.buttonDisconnect.setObjectName("buttonDisconnect")
        self.buttonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.buttonConnect.setGeometry(QtCore.QRect(220, 100, 81, 24))
        self.buttonConnect.setObjectName("buttonConnect")
        self.inputDistance = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputDistance.setGeometry(QtCore.QRect(279, 253, 271, 24))
        self.inputDistance.setObjectName("inputDistance")
        self.titleDistance = QtWidgets.QLabel(self.centralwidget)
        self.titleDistance.setGeometry(QtCore.QRect(279, 229, 56, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleDistance.setFont(font)
        self.titleDistance.setObjectName("titleDistance")
        self.buttonMoveAbsolute = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMoveAbsolute.setGeometry(QtCore.QRect(43, 303, 211, 28))
        self.buttonMoveAbsolute.setObjectName("buttonMoveAbsolute")
        self.inputPosition = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputPosition.setGeometry(QtCore.QRect(43, 257, 211, 24))
        self.inputPosition.setObjectName("inputPosition")
        self.titlePosition = QtWidgets.QLabel(self.centralwidget)
        self.titlePosition.setGeometry(QtCore.QRect(43, 233, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titlePosition.setFont(font)
        self.titlePosition.setObjectName("titlePosition")
        self.selectMotor = QtWidgets.QComboBox(self.centralwidget)
        self.selectMotor.setGeometry(QtCore.QRect(40, 185, 161, 22))
        self.selectMotor.setCurrentText("")
        self.selectMotor.setPlaceholderText("")
        self.selectMotor.setObjectName("selectMotor")
        self.titleSelectMotor = QtWidgets.QLabel(self.centralwidget)
        self.titleSelectMotor.setGeometry(QtCore.QRect(40, 160, 83, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSelectMotor.setFont(font)
        self.titleSelectMotor.setObjectName("titleSelectMotor")
        self.indicatorPosition = QtWidgets.QLCDNumber(self.centralwidget)
        self.indicatorPosition.setGeometry(QtCore.QRect(420, 167, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.indicatorPosition.setFont(font)
        self.indicatorPosition.setObjectName("indicatorPosition")
        self.titleIndicatorPosition = QtWidgets.QLabel(self.centralwidget)
        self.titleIndicatorPosition.setGeometry(QtCore.QRect(420, 150, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleIndicatorPosition.setFont(font)
        self.titleIndicatorPosition.setObjectName("titleIndicatorPosition")
        self.buttonMoveRelativePositive = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMoveRelativePositive.setGeometry(QtCore.QRect(416, 300, 131, 28))
        self.buttonMoveRelativePositive.setObjectName("buttonMoveRelativePositive")
        self.buttonMoveRelativeNegative = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMoveRelativeNegative.setGeometry(QtCore.QRect(280, 300, 131, 28))
        self.buttonMoveRelativeNegative.setObjectName("buttonMoveRelativeNegative")
        self.titleConnection = QtWidgets.QLabel(self.centralwidget)
        self.titleConnection.setGeometry(QtCore.QRect(420, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleConnection.setFont(font)
        self.titleConnection.setObjectName("titleConnection")
        self.ledMoving = QtWidgets.QRadioButton(self.centralwidget)
        self.ledMoving.setGeometry(QtCore.QRect(250, 180, 131, 31))
        self.ledMoving.setStyleSheet("QRadioButton::indicator {\n"
"width: 130px;\n"
"height: 30px\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"background-color: #00ff00;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"background-color: #486c58;\n"
"}\n"
"")
        self.ledMoving.setText("")
        self.ledMoving.setObjectName("ledMoving")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(410, 100, 151, 31))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.ledConnected = QtWidgets.QRadioButton(self.groupBox)
        self.ledConnected.setGeometry(QtCore.QRect(10, 0, 131, 31))
        self.ledConnected.setStyleSheet("QRadioButton::indicator {\n"
"width: 130px;\n"
"height: 30px\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"background-color: #00ff00;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"background-color: #486c58;\n"
"}\n"
"\n"
"")
        self.ledConnected.setText("")
        self.ledConnected.setObjectName("ledConnected")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonStop.setText(_translate("MainWindow", "STOP"))
        self.titleUI.setText(_translate("MainWindow", "MOTION CONTROLLER"))
        self.titleMoving.setText(_translate("MainWindow", "Moving"))
        self.titleController.setText(_translate("MainWindow", "Controller"))
        self.buttonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.buttonConnect.setText(_translate("MainWindow", "Connect"))
        self.titleDistance.setText(_translate("MainWindow", "Distance"))
        self.buttonMoveAbsolute.setText(_translate("MainWindow", "Move Absolute"))
        self.titlePosition.setText(_translate("MainWindow", "Position"))
        self.titleSelectMotor.setText(_translate("MainWindow", "Select Motor"))
        self.titleIndicatorPosition.setText(_translate("MainWindow", "Position"))
        self.buttonMoveRelativePositive.setText(_translate("MainWindow", "Move Relative +"))
        self.buttonMoveRelativeNegative.setText(_translate("MainWindow", "Move Relative -"))
        self.titleConnection.setText(_translate("MainWindow", "Connection"))
