""" This is the file created by Python when translating the .ui file to .py file.
You can always update this file (but this comments will be erased) by using the next command:

pyuic5 <filename.ui> -o <filename.py>

for this case was done in this specific form "pyuic5 main_window.ui -o main_window.py".
I decided to name all the widgets (controllers and indicators) in a mixedCased form to match
the same name convention used by PyQt5.
"""


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(35, 373, 521, 51))
        self.button_stop.setObjectName("button_stop")
        self.title_ui = QtWidgets.QLabel(self.centralwidget)
        self.title_ui.setGeometry(QtCore.QRect(100, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_ui.setFont(font)
        self.title_ui.setObjectName("title_ui")
        self.title_moving = QtWidgets.QLabel(self.centralwidget)
        self.title_moving.setGeometry(QtCore.QRect(220, 160, 64, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_moving.setFont(font)
        self.title_moving.setObjectName("title_moving")
        self.title_controller = QtWidgets.QLabel(self.centralwidget)
        self.title_controller.setGeometry(QtCore.QRect(40, 80, 64, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_controller.setFont(font)
        self.title_controller.setObjectName("title_controller")
        self.select_controller = QtWidgets.QComboBox(self.centralwidget)
        self.select_controller.setGeometry(QtCore.QRect(40, 104, 161, 21))
        self.select_controller.setCurrentText("")
        self.select_controller.setPlaceholderText("")
        self.select_controller.setObjectName("select_controller")
        self.button_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.button_disconnect.setGeometry(QtCore.QRect(320, 100, 81, 24))
        self.button_disconnect.setObjectName("button_disconnect")
        self.button_connect = QtWidgets.QPushButton(self.centralwidget)
        self.button_connect.setGeometry(QtCore.QRect(220, 100, 81, 24))
        self.button_connect.setObjectName("button_connect")
        self.input_distance = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.input_distance.setGeometry(QtCore.QRect(279, 253, 271, 24))
        self.input_distance.setObjectName("input_distance")
        self.title_distance = QtWidgets.QLabel(self.centralwidget)
        self.title_distance.setGeometry(QtCore.QRect(279, 229, 56, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_distance.setFont(font)
        self.title_distance.setObjectName("title_distance")
        self.button_move_absolute = QtWidgets.QPushButton(self.centralwidget)
        self.button_move_absolute.setGeometry(QtCore.QRect(43, 303, 211, 28))
        self.button_move_absolute.setObjectName("button_move_absolute")
        self.input_position = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.input_position.setGeometry(QtCore.QRect(43, 257, 211, 24))
        self.input_position.setObjectName("input_position")
        self.title_position = QtWidgets.QLabel(self.centralwidget)
        self.title_position.setGeometry(QtCore.QRect(43, 233, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_position.setFont(font)
        self.title_position.setObjectName("title_position")
        self.select_motor = QtWidgets.QComboBox(self.centralwidget)
        self.select_motor.setGeometry(QtCore.QRect(40, 185, 161, 22))
        self.select_motor.setCurrentText("")
        self.select_motor.setPlaceholderText("")
        self.select_motor.setObjectName("select_motor")
        self.title_select_motor = QtWidgets.QLabel(self.centralwidget)
        self.title_select_motor.setGeometry(QtCore.QRect(40, 160, 83, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_select_motor.setFont(font)
        self.title_select_motor.setObjectName("title_select_motor")
        self.title_indicator_position = QtWidgets.QLabel(self.centralwidget)
        self.title_indicator_position.setGeometry(QtCore.QRect(420, 150, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_indicator_position.setFont(font)
        self.title_indicator_position.setObjectName("title_indicator_position")
        self.button_move_relative_positive = QtWidgets.QPushButton(self.centralwidget)
        self.button_move_relative_positive.setGeometry(QtCore.QRect(416, 300, 131, 28))
        self.button_move_relative_positive.setObjectName("button_move_relative_positive")
        self.button_move_relative_negative = QtWidgets.QPushButton(self.centralwidget)
        self.button_move_relative_negative.setGeometry(QtCore.QRect(280, 300, 131, 28))
        self.button_move_relative_negative.setObjectName("button_move_relative_negative")
        self.title_connection = QtWidgets.QLabel(self.centralwidget)
        self.title_connection.setGeometry(QtCore.QRect(420, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_connection.setFont(font)
        self.title_connection.setObjectName("title_connection")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(420, 100, 131, 31))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.led_connected = QtWidgets.QRadioButton(self.groupBox)
        self.led_connected.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.led_connected.setStyleSheet("QRadioButton::indicator {\n"
"width: 130px;\n"
"height: 30px\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"background-color: #00ff00;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"background-color: #486c58;\n"
"}\n"
"\n"
"")
        self.led_connected.setText("")
        self.led_connected.setObjectName("led_connected")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 180, 131, 31))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.led_moving = QtWidgets.QRadioButton(self.groupBox_2)
        self.led_moving.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.led_moving.setStyleSheet("QRadioButton::indicator {\n"
"width: 130px;\n"
"height: 30px\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"background-color: #00ff00;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"background-color: #486c58;\n"
"}\n"
"")
        self.led_moving.setText("")
        self.led_moving.setObjectName("led_moving")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(420, 170, 121, 41))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.indicator_position = QtWidgets.QLCDNumber(self.groupBox_3)
        self.indicator_position.setGeometry(QtCore.QRect(0, 0, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.indicator_position.setFont(font)
        self.indicator_position.setObjectName("indicator_position")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_stop.setText(_translate("MainWindow", "STOP"))
        self.title_ui.setText(_translate("MainWindow", "MOTION CONTROLLER"))
        self.title_moving.setText(_translate("MainWindow", "Moving"))
        self.title_controller.setText(_translate("MainWindow", "Controller"))
        self.button_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.title_distance.setText(_translate("MainWindow", "Distance"))
        self.button_move_absolute.setText(_translate("MainWindow", "Move Absolute"))
        self.title_position.setText(_translate("MainWindow", "Position"))
        self.title_select_motor.setText(_translate("MainWindow", "Select Motor"))
        self.title_indicator_position.setText(_translate("MainWindow", "Position"))
        self.button_move_relative_positive.setText(_translate("MainWindow", "Move Relative +"))
        self.button_move_relative_negative.setText(_translate("MainWindow", "Move Relative -"))
        self.title_connection.setText(_translate("MainWindow", "Connection"))
