# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Stop.setGeometry(QtCore.QRect(35, 373, 521, 51))
        self.Button_Stop.setObjectName("Button_Stop")
        self.Title_UI = QtWidgets.QLabel(self.centralwidget)
        self.Title_UI.setGeometry(QtCore.QRect(100, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Title_UI.setFont(font)
        self.Title_UI.setObjectName("Title_UI")
        self.Title_Moving = QtWidgets.QLabel(self.centralwidget)
        self.Title_Moving.setGeometry(QtCore.QRect(250, 160, 64, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_Moving.setFont(font)
        self.Title_Moving.setObjectName("Title_Moving")
        self.Title_Controller = QtWidgets.QLabel(self.centralwidget)
        self.Title_Controller.setGeometry(QtCore.QRect(40, 80, 64, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_Controller.setFont(font)
        self.Title_Controller.setObjectName("Title_Controller")
        self.Select_Controller = QtWidgets.QComboBox(self.centralwidget)
        self.Select_Controller.setGeometry(QtCore.QRect(40, 104, 161, 21))
        self.Select_Controller.setCurrentText("")
        self.Select_Controller.setPlaceholderText("")
        self.Select_Controller.setObjectName("Select_Controller")
        self.Button_Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Disconnect.setGeometry(QtCore.QRect(320, 100, 81, 24))
        self.Button_Disconnect.setObjectName("Button_Disconnect")
        self.Button_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Connect.setGeometry(QtCore.QRect(220, 100, 81, 24))
        self.Button_Connect.setObjectName("Button_Connect")
        self.Input_Distance = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Input_Distance.setGeometry(QtCore.QRect(279, 253, 271, 24))
        self.Input_Distance.setObjectName("Input_Distance")
        self.Title_Distance = QtWidgets.QLabel(self.centralwidget)
        self.Title_Distance.setGeometry(QtCore.QRect(279, 229, 56, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_Distance.setFont(font)
        self.Title_Distance.setObjectName("Title_Distance")
        self.Button_MoveAbsolute = QtWidgets.QPushButton(self.centralwidget)
        self.Button_MoveAbsolute.setGeometry(QtCore.QRect(43, 303, 211, 28))
        self.Button_MoveAbsolute.setObjectName("Button_MoveAbsolute")
        self.Input_Position = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Input_Position.setGeometry(QtCore.QRect(43, 257, 211, 24))
        self.Input_Position.setObjectName("Input_Position")
        self.Title_Position = QtWidgets.QLabel(self.centralwidget)
        self.Title_Position.setGeometry(QtCore.QRect(43, 233, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_Position.setFont(font)
        self.Title_Position.setObjectName("Title_Position")
        self.Select_Motor = QtWidgets.QComboBox(self.centralwidget)
        self.Select_Motor.setGeometry(QtCore.QRect(40, 185, 161, 22))
        self.Select_Motor.setCurrentText("")
        self.Select_Motor.setPlaceholderText("")
        self.Select_Motor.setObjectName("Select_Motor")
        self.Title_SelectMotor = QtWidgets.QLabel(self.centralwidget)
        self.Title_SelectMotor.setGeometry(QtCore.QRect(40, 160, 83, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_SelectMotor.setFont(font)
        self.Title_SelectMotor.setObjectName("Title_SelectMotor")
        self.Indicator_Position = QtWidgets.QLCDNumber(self.centralwidget)
        self.Indicator_Position.setGeometry(QtCore.QRect(420, 167, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Indicator_Position.setFont(font)
        self.Indicator_Position.setObjectName("Indicator_Position")
        self.Title_IndicatorPosition = QtWidgets.QLabel(self.centralwidget)
        self.Title_IndicatorPosition.setGeometry(QtCore.QRect(420, 150, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_IndicatorPosition.setFont(font)
        self.Title_IndicatorPosition.setObjectName("Title_IndicatorPosition")
        self.Button_MoveRelativePositive = QtWidgets.QPushButton(self.centralwidget)
        self.Button_MoveRelativePositive.setGeometry(QtCore.QRect(416, 300, 131, 28))
        self.Button_MoveRelativePositive.setObjectName("Button_MoveRelativePositive")
        self.Button_MoveRelativeNegative = QtWidgets.QPushButton(self.centralwidget)
        self.Button_MoveRelativeNegative.setGeometry(QtCore.QRect(280, 300, 131, 28))
        self.Button_MoveRelativeNegative.setObjectName("Button_MoveRelativeNegative")
        self.Title_Connection = QtWidgets.QLabel(self.centralwidget)
        self.Title_Connection.setGeometry(QtCore.QRect(420, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Title_Connection.setFont(font)
        self.Title_Connection.setObjectName("Title_Connection")
        self.Led_Moving = QtWidgets.QRadioButton(self.centralwidget)
        self.Led_Moving.setGeometry(QtCore.QRect(250, 180, 131, 31))
        self.Led_Moving.setStyleSheet("QRadioButton::indicator {\n"
"width: 130px;\n"
"height: 30px\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"background-color: #00ff00;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"background-color: #486c58;\n"
"}\n"
"")
        self.Led_Moving.setText("")
        self.Led_Moving.setObjectName("Led_Moving")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(410, 100, 151, 31))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Led_Connected = QtWidgets.QRadioButton(self.groupBox)
        self.Led_Connected.setGeometry(QtCore.QRect(10, 0, 131, 31))
        self.Led_Connected.setStyleSheet("QRadioButton::indicator {\n"
"width: 130px;\n"
"height: 30px\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"background-color: #00ff00;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"background-color: #486c58;\n"
"}\n"
"\n"
"")
        self.Led_Connected.setText("")
        self.Led_Connected.setObjectName("Led_Connected")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Stop.setText(_translate("MainWindow", "STOP"))
        self.Title_UI.setText(_translate("MainWindow", "MOTION CONTROLLER"))
        self.Title_Moving.setText(_translate("MainWindow", "Moving"))
        self.Title_Controller.setText(_translate("MainWindow", "Controller"))
        self.Button_Disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.Button_Connect.setText(_translate("MainWindow", "Connect"))
        self.Title_Distance.setText(_translate("MainWindow", "Distance"))
        self.Button_MoveAbsolute.setText(_translate("MainWindow", "Move Absolute"))
        self.Title_Position.setText(_translate("MainWindow", "Position"))
        self.Title_SelectMotor.setText(_translate("MainWindow", "Select Motor"))
        self.Title_IndicatorPosition.setText(_translate("MainWindow", "Position"))
        self.Button_MoveRelativePositive.setText(_translate("MainWindow", "Move Relative +"))
        self.Button_MoveRelativeNegative.setText(_translate("MainWindow", "Move Relative -"))
        self.Title_Connection.setText(_translate("MainWindow", "Connection"))
